version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "${AWS_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    container_name: springboot_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:6500"
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESSTOKEN_EXPIRED: ${JWT_ACCESSTOKEN_EXPIRED}
      JWT_REFRESHTOKEN_EXPIRED: ${JWT_REFRESHTOKEN_EXPIRED}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
