spring:
  application:
    name: korder

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${AWS_DB_HOST}:${AWS_DB_PORT}/${AWS_DB_NAME}
    username: ${AWS_DB_USER}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESSTOKEN_EXPIRED}
  refresh-token-validity: ${JWT_REFRESHTOKEN_EXPIRED}

redis:
  port: ${REDIS_PORT}
  host: ${REDIS_HOST}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

server:
  port: ${APP_PORT}
