spring:
  application:
    name: korder

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESSTOKEN_EXPIRED}
  refresh-token-validity: ${JWT_REFRESHTOKEN_EXPIRED}

#redis
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

#sweger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

sever:
  port: ${APP_PORT}


#Euka 설정
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6501/eureka/