server:
  port: 6503

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/korder-user
    username: korder
    password: hanghae123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6501/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        jpa: DEBUG

jwt:
  secret: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  accesstoken:
    expiration: 3600000
  refreshtoken:
    expiration: 1296000000
