server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/korder_event
    username: korder
    password: hanghae123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        jpa: INFO
      apache:
        hc: INFO
      springframework.web.client.RestTemplate: INFO
      com:
        netflix:
          discovery: INFO
      com.zaxxer.hikari: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
